language: php

services:
  - mysql

branches:
  only:
    - master

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - DB=mysql DB_USER=root

before_script:
  # MySQL
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'SET FOREIGN_KEY_CHECKS = 0; DROP DATABASE IF EXISTS test; DROP SCHEMA IF EXISTS second_hand_books; DROP SCHEMA IF EXISTS contest; DROP DATABASE IF EXISTS reverse_bookstore; DROP SCHEMA IF EXISTS bookstore_schemas; SET FOREIGN_KEY_CHECKS = 1;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE test; CREATE SCHEMA bookstore_schemas; CREATE SCHEMA contest; CREATE SCHEMA second_hand_books; CREATE DATABASE reverse_bookstore;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then echo 'SET GLOBAL sql_mode = '\''STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'\'''; fi"
  # Composer
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --prefer-source

  - ./test/reset_tests.sh

script: vendor/bin/phpunit

