version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /usr/src/app
    tty: true
    volumes:
      - .:/usr/src/app
    depends_on:
      mysql:
         condition: service_healthy
      postgresql:
         condition: service_healthy

  mysql:
    image: mysql:5.7
    command: >
      --sql-mode="NO_ENGINE_SUBSTITUTION"
      --character-set-server="utf8"
      --collation-server="utf8_unicode_ci"
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: "test"
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -e 'select 1'" ]
      interval: 5s
      timeout: 20s
      retries: 30

  postgresql:
    image: postgres:14-bullseye
    environment:
      POSTGRES_PASSWORD: "password"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "su - postgres -c pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    
