version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: /bin/bash docker/run.sh 
    volumes:
      - ../:/usr/src/app
    depends_on:
      - db

  db:
    image: percona
    command: >
      mysqld
      --sql-mode="NO_ENGINE_SUBSTITUTION"
      --character-set-server="utf8"
      --collation-server="utf8_unicode_ci"
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
